# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/78ae571a-ec90-45c8-af36-24372aa598d0/transcription
Content-Type: application/json

{
  "prompt": "pouso, porta-aviões"
}

//"id": "78ae571a-ec90-45c8-af36-24372aa598d0"
//example-42c237a8-01ab-4b21-80dc-e4df9c24badc.mp3

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "78ae571a-ec90-45c8-af36-24372aa598d0",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''"
}